import { useEffect, useState } from 'react';
import { usePageReveal } from '../hooks/useRevealOnScroll';
import blog1 from '../assets/blog/blog1.jpg';
import blog2 from '../assets/blog/blog2.jpg';
import blog3 from '../assets/blog/blog3.jpg';
import blog4 from '../assets/blog/blog4.jpg';

const POSTS_CONTENT = {
  cdp: {
    title: 'Customer Data Platform (formerly Salesforce CDP)',
    img: blog1,
    meta: {
      author: 'By amit goyal',
      date: 'February 3, 2023',
    },
    intro: 'Customer Data Platform, formerly known as Salesforce CDP, helps you create a single source of truth (SSOT) so you can get to know your customers and engage with relevance. Admins can use the CRM Analytics dashboards to augment your analysis without moving the data from Customer Data Platform.',
    desc: 'Salesforce CDP Has Been Changed to Customer Data Platform',
    bodyText: 'Salesforce CDP is now called Customer Data Platform. We\'re in the process of updating the name in the UI, documentation, Trailhead, and more.',
    items: [
      {
        heading: 'Retain Data After Deleting a Data Stream',
        text: 'You can now seamlessly delete an S3 data stream and retain its associated data lake object (DLO) because the data stream and DLO are decoupled. You can also choose to reuse an existing DLO while configuring a new S3 data stream.'
      },
      {
        heading: 'Access CRM Analytics with One Click',
        text: 'Explore and analyze your Customer Data Platform data in CRM Analytics with a single click. You can augment your analysis without moving the data from Customer Data Platform. In Customer Data Platform, select a data object, and click the new Explore in Analytics button to use the CRM Analytics dashboards.'
      },
      {
        heading: 'Identify Skipped Ruleset Jobs',
        text: 'Ruleset jobs that aren\'t scheduled to run are now tagged with the Skipped status in the ruleset\'s Processing History tab. The Skipped status applies when a ruleset job isn\'t scheduled. Ruleset jobs are skipped if there were no changes to data streams or records in the source data model object, and the ruleset\'s configuration remains unchanged.'
      },
      {
        heading: 'Identify Problems with Identity Resolution Rulesets',
        text: 'Ruleset warnings identify specific mappings, rules, or fields to review to improve profile unification consolidation rate and reduce the number of unified profiles counted against your contracted entitlement. For example, reconciliation rules warnings prompt you to select the Source Sequence reconciliation rule as a way to reduce the frequency of value changes in ID fields.'
      },
      {
        heading: 'Build and Share',
        text: 'Insight Builder is a business-analyst-focused and user-friendly metrics authoring tool that is used to create an insight. Using the visual builder, you can generate the required data sets similar to the ones generated by using SQL.'
      },
      {
        heading: 'Reuse Segments (Beta)',
        text: 'Save time and maintain consistency by building segments from existing segments.'
      },
      {
        heading: 'Narrow Segments with Exclusion Criteria (Beta)',
        text: 'Use the new Exclude tab to narrow your audience using exclusion criteria.'
      },
      {
        heading: 'Accelerate Data Processing Between Customer Data Platform and Tableau (Pilot)',
        text: 'The new Hyper Query Processing engine performs faster query processing on large and complex datasets. The query engine is native to Customer Data Platform and speeds up interactive analytics when customers query data in Tableau from Customer Data Platform.'
      }
    ],
    prevPost: null,
    nextPost: 'einstein'
  },
  einstein: {
    title: 'Einstein',
    img: blog2,
    meta: {
      author: 'By amit goyal',
      date: 'February 3, 2023',
    },
    intro: 'Make it easier for service agents to find knowledge articles with Einstein Search for Knowledge, now generally available. Use live Snowflake data with your Einstein Discovery models and enjoy a more flexible source of truth.',
    desc: 'Ramp up quickly with new learning maps for Einstein Bots and Einstein Prediction Builder, plus a new welcome experience for Einstein Conversation Insights managers and reps. Customizable dashboards help you show the value of your Einstein Article Recommendations and Einstein Reply Recommendations setups.',
    bodyText: 'Rights of ALBERT EINSTEIN are used with permission of The Hebrew University of Jerusalem. Represented exclusively by Greenlight.',
    items: [
      {
        heading: 'Salesforce Overall',
        subheading: 'Einstein Search',
        text: 'Einstein Search provides an improved search experience at no additional cost. Einstein Search for Knowledge, which is now generally available, makes it easier for service agents to locate relevant articles. Users can also interact with new Einstein Search Answers enhancements and save answers and links to their clipboards.'
      },
      {
        heading: 'Analytics',
        subheading: 'Einstein Discovery',
        text: 'Deploy models to make predictions with Snowflake data. Identify the most important variables in your model. Get fine-grain model performance of values within variables. See estimated story run time.'
      },
      {
        heading: 'Customization',
        subheading: 'Einstein Prediction Builder',
        text: 'Build effective custom AI predictions by using the Einstein Prediction Builder Learning Map. This one-stop solution shows you how to build, from exploration to troubleshooting. Get valuable insights to drive predictive intelligence for your business.'
      },
      {
        heading: 'Development',
        subheading: 'Einstein Vision and Language',
        text: 'Discover Einstein Vision and Language on the Salesforce Developer Portal and enjoy a more integrated content experience.'
      },
      {
        heading: 'Industries',
        subheading: 'AI Accelerator',
        text: 'Integrate AI Accelerator and Next Best Actions (NBA) for your real-time use cases and show real-time predictions and NBA recommendations on one component. Use the Recommendations Connect API to get recommendations from the predictions generated for your use case.'
      },
      {
        heading: 'Einstein Relationship Insights',
        text: 'Get updates when Einstein finds relationship recommendations for the records that you follow. View Relationship Insights from the new Actionable Relationship Center component.'
      },
      {
        heading: 'Intelligent Document Reader',
        text: 'Entering information from a handwritten intake application can be a tedious, error-prone, manual process. Intelligent Document Reader uses your AWS account to access Amazon Textract to get the correct data from the correct documents faster. With Intelligent Document Reader, data from uploaded documents such as applicants\' identity and contact information is directly pulled into an online application record, reducing manual document input and management.'
      },
      {
        heading: 'Intelligent Form Reader',
        text: 'Store data extracted from tables in a form.'
      },
      {
        heading: 'Sentiment Insights',
        text: 'Analyze customer sentiment with a dedicated AWS account using the Amazon Comprehend BatchDetectSentiment API. Sentiment Insights categorizes customer sentiment as positive, negative, mixed, or neutral. Analyze customer sentiment on responses to text-based survey questions, identify positive and negative trends, and discover areas of improvement.'
      },
      {
        heading: 'Sales',
        subheading: 'Einstein Conversation Insights',
        text: 'Einstein Conversation Insights now includes a welcome experience for new users. Sales reps and managers can also see insights related to customer objections and get faster access to processed calls.'
      },
      {
        heading: 'Sales Cloud Einstein',
        text: 'The lead and opportunity scoring model refresh schedule changed.'
      },
      {
        heading: 'Service',
        subheading: 'Einstein Classification',
        text: 'Include encrypted fields when you build your Case Classification model, and deflect cases and improve case handling time by integrating Case Classification with Flows.'
      },
      {
        heading: 'Einstein Article Recommendations',
        text: 'Quantify the value of your Einstein setup with a customizable dashboard for Einstein Article Recommendations.'
      },
      {
        heading: 'Einstein Reply Recommendations',
        text: 'Quantify the value of your Einstein setup with a customizable dashboard for Einstein Reply Recommendations, and keep your Reply Recommendations model fresh with automatic monthly retraining.'
      },
      {
        heading: 'Einstein Bots',
        text: 'We\'re making it easier to learn about Einstein Bots and make smart performance decisions. Admins and developers can find everything they need to know about building, launching, and extending bots in the new Learning Map. Dig deeper into bot performance with new metric types and standard reports. Monitor your bot session use with engaged sessions.'
      }
    ],
    prevPost: 'cdp',
    nextPost: 'commerce'
  },
  commerce: {
    title: 'Commerce',
    img: blog3,
    meta: {
      author: 'By amit goyal',
      date: 'February 2, 2023',
    },
    intro: 'Commerce Cloud enhancements include new and updated features for B2B and B2B2C Commerce, Omnichannel Inventory, Salesforce Order Management, and Salesforce Payments.',
    desc: '',
    bodyText: '',
    items: [
      {
        heading: 'B2B and B2B2C Commerce',
        text: 'Use expanded global selling features to add multiple languages and sell in more countries. Quickly set up taxes using the new included tax solution. Use the expanded promotions features, including promotion limits and updated priority rules. Get more guidance during product import. Use expressions in component text fields, and create a B2C store on an existing site.'
      },
      {
        heading: 'Salesforce Order Management',
        text: 'Create orders on behalf of shoppers. Ingest orders at high scale. Charge return fees, and select the payment method for a refund. And you can now record a reason when rejecting fulfillment order items.'
      },
      {
        heading: 'Salesforce Payments',
        text: 'Offer shoppers a smooth and secure checkout experience with Salesforce Payments, available for Salesforce B2C Commerce and as a new application on the Salesforce platform. Simplify integration with Salesforce B2B2C Commerce and Salesforce Order Management, protect against fraud, and access payments reports for data insights.'
      }
    ],
    prevPost: 'einstein',
    nextPost: 'dev'
  },
  dev: {
    title: 'Development',
    img: blog4,
    meta: {
      author: 'By amit goyal',
      date: 'February 2, 2023',
    },
    intro: 'Whether you\'re using Lightning components, Visualforce, Apex, or our APIs with your favorite programming language, these enhancements help you develop amazing applications, integrations, and packages for resale to other organizations.',
    desc: '',
    bodyText: '',
    items: [
      {
        heading: 'Lightning Components',
        text: 'Invalid HTML syntax in your LWC markup now results in a runtime error. Lightning Web Security is enabled by default in new Salesforce orgs.'
      },
      {
        heading: 'Einstein Vision and Language',
        text: 'Discover Einstein Vision and Language on the Salesforce Developer Portal and enjoy a more integrated content experience.'
      },
      {
        heading: 'Visualforce',
        text: 'Increase the security of your Visualforce pages by reviewing and enabling the release updates. For more information on features affected by these enhancements, refer to the Visualforce Developer Guide.'
      },
      {
        heading: 'Apex',
        text: 'Data Weave in Apex is now in Developer Preview. Run more operations in user mode using enhanced System. Database methods. Improve the readability of your Apex code by using the new System. Assert class methods. Reference the new order of execution diagram, which depicts the order in which events are applied when you save a record in Salesforce. Enjoy improved access to query results via reduced cursor limits. Use the Daily Async Apex Tests limit that is now exposed. This limit represents the number of Apex test classes that can be queued in a 24-hour period. Call invocable actions from Apex code using the Invocable. Action class methods.'
      },
      {
        heading: 'API',
        text: 'These items are new, changed, or deprecated in API version 56.0.'
      },
      {
        heading: 'API',
        subheading: 'Packaging',
        text: 'Transfer the ownership of an unlocked or second-generation managed package from one Dev Hub org to another. Update your packages for enhanced domains and partitioned domains. Do more with increased limits on feature parameters, and understand the components available in managed packages better with expanded documentation.'
      },
      {
        heading: 'API',
        subheading: 'Development Environments',
        text: 'Development environments are full-featured Salesforce environments that you use to develop and test existing or new features and custom applications. They include Developer Edition orgs, sandboxes, and scratch orgs.'
      },
      {
        heading: 'API',
        subheading: 'Platform Development Tools',
        text: 'Build applications collaboratively and deliver continuously with Salesforce Developer Experience (DX), the open and integrated experience that makes development on the Customer 360 Platform easy.'
      },
      {
        heading: 'API',
        subheading: 'DevOps Center (Generally Available)',
        text: 'Salesforce DevOps Center provides an improved experience around change and release management that brings DevOps best practices to your development team, regardless of where team members fall on the low-code to pro-code spectrum. All developers and builders can work together to deliver value to customers in a repeatable and scalable way.'
      },
      {
        heading: 'API',
        subheading: 'Salesforce Functions',
        text: 'Salesforce Functions extends the power of Salesforce with elastic compute and language flexibility.'
      },
      {
        heading: 'AppExchange Partners',
        text: 'Access the AppExchange Developer Center, a curated library of resources to help you build solutions faster using the latest Salesforce technology'
      },
      {
        heading: 'Change Data Capture',
        text: 'Filter streams of change events.'
      },
      {
        heading: 'Platform Events',
        text: 'Filter platform event streams, monitor event usage in Setup, and monitor the daily event delivery usage in REST API.'
      },
      {
        heading: 'Event Bus',
        text: 'Stream your Salesforce events to Amazon EventBridge. Use Pub/Sub API to publish and subscribe to events.'
      },
      {
        heading: 'New and Changed Items for Developers',
        text: 'Here is where you can find new and changed objects, calls, classes, components, commands, and more that help you customize Salesforce features.'
      }
    ],
    prevPost: 'commerce',
    nextPost: null
  }
};

function BlogPage() {
  const [activePost, setActivePost] = useState(null); // null, 'cdp', 'einstein', 'commerce', 'dev'
  const [commentName, setCommentName] = useState('');
  const [commentEmail, setCommentEmail] = useState('');
  const [commentWebsite, setCommentWebsite] = useState('');

  // Check URL query string on mount for a specific post
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const post = params.get('post');
    if (post && POSTS_CONTENT[post]) {
      setActivePost(post);
    }
  }, []);
  const [commentText, setCommentText] = useState('');
  const [saveDetails, setSaveDetails] = useState(false);
  const [commentSubmitted, setCommentSubmitted] = useState(false);

  usePageReveal('.blog-reveal', { threshold: 0.02, rootMargin: '0px 0px -40px 0px' }, [activePost]);

  const handleCommentSubmit = (e) => {
    e.preventDefault();
    if (!commentText || !commentName || !commentEmail) return;
    setCommentSubmitted(true);
    setTimeout(() => {
      setCommentSubmitted(false);
      setCommentText('');
      if (!saveDetails) {
        setCommentName('');
        setCommentEmail('');
        setCommentWebsite('');
      }
    }, 3000);
  };

  if (activePost) {
    const post = POSTS_CONTENT[activePost];

    return (
      <div className="blog-page w-full">
          <div className="blog-wrap">
          
          {/* Breadcrumb Navigation */}
          <div className="blog-reveal">
            <button 
              onClick={() => setActivePost(null)}
              className="blog-detail-back-btn"
            >
              <svg className="w-4 h-4 transition-transform duration-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              Back to articles
            </button>
          </div>

          <div className="blog-detail-container blog-reveal">
            
            {/* Meta badges */}
            <div className="blog-detail-meta-row">
              <span className="blog-meta-badge author">
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                </svg>
                {post.meta.author}
              </span>
              <span className="blog-meta-badge date">
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                {post.meta.date}
              </span>
              <span className="blog-meta-badge comments">
                <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                </svg>
                Leave a Comment
              </span>
            </div>

            {/* Title */}
            <h1 className="blog-detail-title">{post.title}</h1>

            {/* Main Image */}
            <div className="blog-detail-img-wrap">
              <img src={post.img} alt={post.title} className="blog-detail-img" />
            </div>

            {/* Detailed Body content */}
            <div className="blog-detail-body">
              <p className="blog-detail-intro">
                {post.intro}
              </p>

              <div className="blog-detail-note">
                <strong>Description:</strong> {post.desc}
              </div>

              <p>
                {post.bodyText}
              </p>

              <div className="blog-detail-sections">
                {post.items.map((item, idx) => (
                  <div key={idx} className="blog-detail-item">
                    <h4>{item.heading}</h4>
                    {item.subheading && <div className="blog-detail-subheading">&ndash; {item.subheading}</div>}
                    <p>{item.text}</p>
                  </div>
                ))}
              </div>

              {/* Prev / Next links */}
              <div className="blog-detail-prev-wrap">
                {post.prevPost ? (
                  <button onClick={() => setActivePost(post.prevPost)} className="blog-detail-prev-link">
                    &larr; Previous Post
                  </button>
                ) : (
                  <span />
                )}
                {post.nextPost ? (
                  <button onClick={() => setActivePost(post.nextPost)} className="blog-detail-next-link">
                    Next Post &rarr;
                  </button>
                ) : (
                  <span />
                )}
              </div>

              {/* Leave a Comment */}
              <div className="blog-detail-comment-form">
                <h3>Leave a Comment</h3>
                <p className="blog-detail-comment-subtitle">Your email address will not be published. Required fields are marked *</p>

                {commentSubmitted ? (
                  <div className="comment-success-alert">
                    ✓ Thank you! Your comment has been submitted for review.
                  </div>
                ) : (
                  <form onSubmit={handleCommentSubmit} className="blog-detail-form">
                    <div className="blog-detail-form-group">
                      <div className="blog-floating-group">
                        <textarea
                          value={commentText}
                          onChange={(e) => setCommentText(e.target.value)}
                          placeholder=" "
                          rows={6}
                          required
                          className="blog-floating-textarea"
                        />
                        <label className="blog-floating-label">Type here..</label>
                      </div>
                    </div>

                    <div className="blog-detail-form-row">
                      <div className="blog-floating-group">
                        <input
                          type="text"
                          value={commentName}
                          onChange={(e) => setCommentName(e.target.value)}
                          placeholder=" "
                          required
                          className="blog-floating-input"
                        />
                        <label className="blog-floating-label">Name*</label>
                      </div>
                      
                      <div className="blog-floating-group">
                        <input
                          type="email"
                          value={commentEmail}
                          onChange={(e) => setCommentEmail(e.target.value)}
                          placeholder=" "
                          required
                          className="blog-floating-input"
                        />
                        <label className="blog-floating-label">Email*</label>
                      </div>

                      <div className="blog-floating-group">
                        <input
                          type="text"
                          value={commentWebsite}
                          onChange={(e) => setCommentWebsite(e.target.value)}
                          placeholder=" "
                          className="blog-floating-input"
                        />
                        <label className="blog-floating-label">Website</label>
                      </div>
                    </div>

                    <div className="blog-detail-checkbox-group">
                      <input
                        type="checkbox"
                        id="save-details"
                        checked={saveDetails}
                        onChange={(e) => setSaveDetails(e.target.checked)}
                      />
                      <label htmlFor="save-details">
                        Save my name, email, and website in this browser for the next time I comment.
                      </label>
                    </div>

                    <button type="submit" className="blog-detail-submit">
                      Post Comment &raquo;
                    </button>
                  </form>
                )}
              </div>

            </div>

          </div>

        </div>
      </div>
    );
  }

  return (
    <div className="blog-page w-full">
      <div className="blog-wrap">
        
        <div className="blog-top blog-reveal">
          <div>
            <div className="blog-eyebrow">Resources &amp; news</div>
            <h2 className="blog-headline">Articles built for <span>builders</span></h2>
          </div>
          <p>Product updates, engineering notes, and Salesforce know-how from the team behind Klique.</p>
        </div>

        <div className="blog-layout">

          <div className="blog-feature blog-reveal">
            <img src={blog1} alt="Customer Data Platform" loading="lazy" />
            <div className="blog-feature-content">
              <span className="blog-feature-tag">Salesforce · Featured</span>
              <h3>Customer Data Platform (formerly Salesforce CDP)</h3>
              <p>Customer Data Platform, formerly Salesforce CDP, unifies customer data across every touchpoint...</p>
              <button 
                onClick={() => setActivePost('cdp')}
                className="blog-feature-link"
              >
                Read More
                <svg viewBox="0 0 24 24" fill="none" strokeWidth="2.4" strokeLinecap="round">
                  <path d="M5 12h14M13 6l6 6-6 6" />
                </svg>
              </button>
            </div>
          </div>

          <div className="blog-side-list">

            <div className="blog-row-card blog-reveal" style={{ animationDelay: '0.1s' }}>
              <div className="blog-row-thumb">
                <img src={blog2} alt="Einstein" loading="lazy" />
              </div>
              <div className="blog-row-body">
                <div className="blog-row-meta">Einstein</div>
                <h4>Einstein</h4>
                <span className="time">Einstein makes it easier for service agents to find knowledge...</span>
                <button 
                  onClick={() => setActivePost('einstein')}
                  className="blog-row-readmore"
                >
                  Read More
                  <svg viewBox="0 0 24 24" fill="none" strokeWidth="2.4" strokeLinecap="round">
                    <path d="M5 12h14M13 6l6 6-6 6" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="blog-row-card blog-reveal" style={{ animationDelay: '0.2s' }}>
              <div className="blog-row-thumb">
                <img src={blog3} alt="Commerce" loading="lazy" />
              </div>
              <div className="blog-row-body">
                <div className="blog-row-meta">Commerce</div>
                <h4>Commerce</h4>
                <span className="time">Commerce Cloud enhancements include new and updated features for...</span>
                <button 
                  onClick={() => setActivePost('commerce')}
                  className="blog-row-readmore"
                >
                  Read More
                  <svg viewBox="0 0 24 24" fill="none" strokeWidth="2.4" strokeLinecap="round">
                    <path d="M5 12h14M13 6l6 6-6 6" />
                  </svg>
                </button>
              </div>
            </div>

            <div className="blog-row-card blog-reveal" style={{ animationDelay: '0.3s' }}>
              <div className="blog-row-thumb">
                <img src={blog4} alt="Development" loading="lazy" />
              </div>
              <div className="blog-row-body">
                <div className="blog-row-meta">Development</div>
                <h4>Development</h4>
                <span className="time">Whether you're using Lightning components, Visualforce, Apex, or our...</span>
                <button 
                  onClick={() => setActivePost('dev')}
                  className="blog-row-readmore"
                >
                  Read More
                  <svg viewBox="0 0 24 24" fill="none" strokeWidth="2.4" strokeLinecap="round">
                    <path d="M5 12h14M13 6l6 6-6 6" />
                  </svg>
                </button>
              </div>
            </div>


          </div>

        </div>
      </div>
    </div>
  );
}

export default BlogPage;
